### ISSUE TITLE
When loading the graph, the following node types were not found

### ISSUE THREAD

**Issue by Mineyme** [evanspearman/ComfyMath#5] opened 2024-01-19 09:39 UTC
I have download  the code ,and then restart .why it  also remind the same wrong: 

![image](https://github.com/evanspearman/ComfyMath/assets/108466614/a3e7c55c-3718-41b9-a7bd-7bb7f54609d8)

![image](https://github.com/evanspearman/ComfyMath/assets/108466614/d67ff7b5-b523-49db-b05b-294a16b0b810)

**Comment by evanspearman** [comment] 2024-09-02 15:49
Can't reproduce this. Closing.

**Closed as completed by evanspearman** 2024-09-02 15:49 UTC
